name: Build Rick and Mortys app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Check
    steps:
      - uses: actions@checkout@v2
      - name: Checkout the code
        uses: ./.github/actions/my-action
      
      - name: Run lint
        run: ./gradlew lintDebug
      
      - name: Upload lint HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html
          
  package:
    needs: [ lint ]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
    
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Upload generated APK
        uses: ./.github/actions/upload-artifact@v2
        with:
          name: rickmortys.apk
          path: app/build/outputs/apk/debug/app-debug.apk
